version: "3.3"

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
      # ports from container exposed to the docker machine and the guest machine
    ports:
      - "9999:9999"
    # Waits that db is ready and starts.
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_USER: juan
      MYSQL_PASSWORD: juan
      MYSQL_ROOT_PASSWORD: juan
      MYSQL_DATABASE: amaro
    ports:
      - "3306"
    volumes:
      - amaro-docker-data:/var/lib/mysql

      # persisted storage
volumes:
  amaro-docker-data:
