openapi: 3.0.3
info:
  title: th-amaro
  version: 0.2.4
  description: Backend challenge
  contact:
    email: juanfarberjob@gmail.com
servers:
  - url: "http://localhost:9999"
    description: Local API
tags:
  - name: Test
    description: Test to see if the API is up

paths:
  /hello:
    get:
      tags:
        - Test
      summary: Test to see if the API is up
      description: Test to see if the API is up
      responses:
        "200":
          description: Succesful operation.
