openapi: 3.0.3
info:
  title: th-amaro
  version: 0.2.4
  description: Backend challenge
  contact:
    email: juanfarberjob@gmail.com
servers:
  - url: "http://localhost:9999"
    description: Local API
tags:
  - name: Test
    description: Test to see if the API is up
  - name: Products
    description: Products insertions and retrievals

paths:
  /hello:
    get:
      tags:
        - Test
      summary: Test to see if the API is up
      description: Test to see if the API is up
      responses:
        "200":
          description: Succesful operation.

  /products/batch-insert:
    post:
      tags:
        - Products
      summary: Batch insertion of products and tags.
      description: Batch insertion of products and tags.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                products:
                  type: array
                  items:
                    type: object
                    properties:
                      id:
                        description: Product ID
                        type: integer
                        example: 8371
                      name:
                        description: Product name
                        type: string
                        example: VESTIDO TRICOT CHEVRON
                      tags:
                        description: Product tags
                        type: array
                        example: ["balada", "neutro", "delicado", "festa"]
              required:
                - products
      responses:
        "200":
          description: Succesful operation.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    description: Operation status message.
                    type: string
                    example: Succesful inserts.
                  data:
                    description: Products inserted succesfully.
                    type: array
                    items:
                      type: string
                      example: VESTIDO TRICOT CHEVRON
        "207":
          description: Multi status. Some failed, but could finish gracefully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    description: Operation status message.
                    type: string
                    example: "ERROR. Failed:"
                  data:
                    description: Products inserted succesfully before the error occurred.
                    type: array
                    items:
                      type: object
                      properties:
                        id_product:
                          type: number
                          example: 8371
                        tags:
                          description: Product tags
                          type: array
                          example: ["balada", "neutro", "delicado", "festa"]
                        error:
                          type: object
                          example:
                            {
                              "Number": 1644,
                              "Message": "id_product already exists.",
                            }
        "500":
          description: Internal server error. Some succeded, but could not finish gracefully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    description: Operation status message.
                    type: string
                    example: "ERROR. Succesful inserts:"
                  data:
                    description: Products inserted succesfully before the error occurred.
                    type: array
                    items:
                      type: string
                      example: VESTIDO TRICOT CHEVRON
